INSERT INTO `shop`.`categories` (`name`, `type`, `groupId`) VALUES
            ('Transport', 'group', NULL),
            ('Imobiliare', 'group', NULL),
            ('Aparate telefonice si gadget-uri', 'group', NULL),
            ('Calculatoare si birotica', 'group', NULL),
            ('Constructii si reparatii', 'group', NULL),
            ('Haine, încaltaminte si accesorii', 'group', NULL),
            ('Mobila si interior', 'group', NULL),
            ('Mobila si interior', 'group', NULL),
            ('Audio-Video-Foto', 'group', NULL),
            ('Diverse', 'group', NULL),
            ('Oferte de lucru', 'group', NULL),
            ('Gospodaria taraneasca', 'group', NULL),
            ('Servicii', 'group', NULL),
            ('Animale de companie si plante', 'group', NULL),
            ('Sport, sanatate, frumusete', 'group', NULL),
            ('Turism, recreatie si divertisment', 'group', NULL),
            ('Business', 'group', NULL),
            ('Instrumente muzicale', 'group', NULL),
            ('Tehnica de uz casnic', 'group', NULL),
            ('Totul pentru sarbatori', 'group', NULL),
            ('Lumea copiilor', 'group', NULL),
            ('Totul pentru casa si oficiu', 'group', NULL),
            ('Mijloace de transport', 'category', 1),
            ('Alte mijloace de transport', 'category', 1),
            ('Piese și accesorii auto', 'category', 1),
            ('Auto multimedia', 'category', 1),
            ('Accesorii auto', 'category', 1),
            ('Scule și echipamente speciale', 'category', 1),
            ('Autochimie', 'category', 1),
            ('Aditivi', 'category', 1),
            ('Servicii auto, transport', 'category', 1),
            ('Cosmetice curățare caroserie', 'category', 1),
            ('Cosmetică auto', 'category', 1),
            ('Autoturisme', 'sub-category', 23),
            ('Autobuze și microbuze', 'sub-category', 23),
            ('Camioane', 'sub-category', 23),
            ('Biciclete', 'sub-category', 23),
            ('Hoverboard-uri, trotinete electrice', 'sub-category', 23),
            ('Mașini agricole', 'sub-category', 24),
            ('Tehnică specializată', 'sub-category', 24),
            ('Remorci, rulote', 'sub-category', 24),
            ('Utilaje pentru construcții', 'sub-category', 24),
            ('Automobile de epocă și exponate auto', 'sub-category', 24),
            ('Ambarcațiuni', 'sub-category', 24),
            ('Vehicule aeriene', 'sub-category', 24),
            ('Jante și anvelope', 'sub-category', 25),
            ('Piese de schimb și dezmembrare autoturisme', 'sub-category', 25),
            ('Echipamente moto', 'sub-category', 25),
            ('Piese de schimb pentru camioane', 'sub-category', 25),
            ('Oglinzi, parbrize și lumini auto', 'sub-category', 25),
            ('Piese moto', 'sub-category', 25),
            ('Piese și accesorii biciclete', 'sub-category', 25),
            ('Acumulatoare', 'sub-category', 25),
            ('Radiocasetofoane și DVD', 'sub-category', 26),
            ('Sisteme audio auto', 'sub-category', 26),
            ('Camere video auto', 'sub-category', 26),
            ('Sisteme de navigație, GPS', 'sub-category', 26),
            ('Componente audio auto', 'sub-category', 26),
            ('Detectoare radar, alarme', 'sub-category', 26),
            ('Accesorii pentru salon', 'sub-category', 27),
            ('Covorașe pentru mașină', 'sub-category', 27),
            ('Vopsea Auto', 'sub-category', 27),
            ('Ajutor tehnic', 'sub-category', 27),
            ('Accesorii pentru caroserie', 'sub-category', 27),
            ('Scaune auto pentru copii', 'sub-category', 27),
            ('Portbagaje auto', 'sub-category', 27),
            ('Carinaj', 'sub-category', 27),
            ('Parktronic', 'sub-category', 27),
            ('Chei auto', 'sub-category', 27),
            ('Chei', 'sub-category', 28),
            ('Cricuri', 'sub-category', 28),
            ('Ascensoare', 'sub-category', 28),
            ('Demontatoare', 'sub-category', 28),
            ('Compresoare auto', 'sub-category', 28),
            ('Standuri de aliniere', 'sub-category', 28),
            ('Încărcătoare de baterii auto', 'sub-category', 28),
            ('Aparate de spălat cu presiune', 'sub-category', 28),
            ('Echipamente de diagnoză', 'sub-category', 28),
            ('Echipament pentru montarea anvelopelor', 'sub-category', 28),
            ('Echipamente hidraulice si mecanice', 'sub-category', 28),
            ('Mobilier pentru stații de service', 'sub-category', 28),
            ('Unelte de lubrifiere', 'sub-category', 28),
            ('Echipamente de caroserie', 'sub-category', 28),
            ('Echipamente suplimentare', 'sub-category', 28),
            ('Uleiuri hidraulice', 'sub-category', 29),
            ('Uleiuri de viteze', 'sub-category', 29),
            ('Antigel', 'sub-category', 29),
            ('Lichid de frînă', 'sub-category', 29),
            ('Lubrifianți', 'sub-category', 29),
            ('Uleiuri de motor', 'sub-category', 29),
            ('Lichide de spălat', 'sub-category', 29),
            ('Aditivi în ulei', 'sub-category', 30),
            ('Aditivi pentru combustibil', 'sub-category', 30),
            ('Aditivi pentru uleiul de viteze', 'sub-category', 30),
            ('Soluții de curățare', 'sub-category', 30),
            ('Aditivi pentru combustibil și dispersanți', 'sub-category', 30),
            ('Autoservice', 'sub-category', 31),
            ('Servicii de transport mărfuri', 'sub-category', 31),
            ('Livrare din magazine', 'sub-category', 31),
            ('Auto la comandă', 'sub-category', 31),
            ('Servicii de transport pasageri', 'sub-category', 31),
            ('Мotoservice și veloservice', 'sub-category', 31),
            ('Închirieri transport', 'sub-category', 31),
            ('Accesorii spălat auto', 'sub-category', 32),
            ('Șampon auto', 'sub-category', 32),
            ('Detergenți pentru caroserie', 'sub-category', 32),
            ('Polish auto', 'sub-category', 33),
            ('Soluții protecție caroserie', 'sub-category', 33),
            ('Cosmetică auto pentru interior', 'sub-category', 33),
            ('Cosmetică auto pentru jante', 'sub-category', 33),
            ('Cosmetică auto pentru sticlă și faruri', 'sub-category', 33)
