INSERT INTO `shop`.`categories` (`name`, `type`, `groupId`) VALUES
            ('Transport', 'group', NULL),
            ('Imobiliare', 'group', NULL),
            ('Aparate telefonice si gadget-uri', 'group', NULL),
            ('Calculatoare si birotica', 'group', NULL),
            ('Constructii si reparatii', 'group', NULL),
            ('Haine, incaltaminte si accesorii', 'group', NULL),
            ('Mobila si interior', 'group', NULL),
            ('Mobila si interior', 'group', NULL),
            ('Audio-Video-Foto', 'group', NULL),
            ('Diverse', 'group', NULL),
            ('Oferte de lucru', 'group', NULL),
            ('Gospodaria taraneasca', 'group', NULL),
            ('Servicii', 'group', NULL),
            ('Animale de companie si plante', 'group', NULL),
            ('Sport, sanatate, frumusete', 'group', NULL),
            ('Turism, recreatie si divertisment', 'group', NULL),
            ('Business', 'group', NULL),
            ('Instrumente muzicale', 'group', NULL),
            ('Tehnica de uz casnic', 'group', NULL),
            ('Totul pentru sarbatori', 'group', NULL),
            ('Lumea copiilor', 'group', NULL),
            ('Totul pentru casa si oficiu', 'group', NULL),
            ('Mijloace de transport', 'category', 1),
            ('Alte mijloace de transport', 'category', 1),
            ('Piese si accesorii auto', 'category', 1),
            ('Auto multimedia', 'category', 1),
            ('Accesorii auto', 'category', 1),
            ('Scule si echipamente speciale', 'category', 1),
            ('Autochimie', 'category', 1),
            ('Aditivi', 'category', 1),
            ('Servicii auto, transport', 'category', 1),
            ('Cosmetice curatare caroserie', 'category', 1),
            ('Cosmetica auto', 'category', 1),
            ('Autoturisme', 'sub-category', 23),
            ('Autobuze si microbuze', 'sub-category', 23),
            ('Camioane', 'sub-category', 23),
            ('Biciclete', 'sub-category', 23),
            ('Hoverboard-uri, trotinete electrice', 'sub-category', 23),
            ('Masini agricole', 'sub-category', 24),
            ('Tehnica specializata', 'sub-category', 24),
            ('Remorci, rulote', 'sub-category', 24),
            ('Utilaje pentru constructii', 'sub-category', 24),
            ('Automobile de epoca si exponate auto', 'sub-category', 24),
            ('Ambarcatiuni', 'sub-category', 24),
            ('Vehicule aeriene', 'sub-category', 24),
            ('Jante si anvelope', 'sub-category', 25),
            ('Piese de schimb si dezmembrare autoturisme', 'sub-category', 25),
            ('Echipamente moto', 'sub-category', 25),
            ('Piese de schimb pentru camioane', 'sub-category', 25),
            ('Oglinzi, parbrize si lumini auto', 'sub-category', 25),
            ('Piese moto', 'sub-category', 25),
            ('Piese si accesorii biciclete', 'sub-category', 25),
            ('Acumulatoare', 'sub-category', 25),
            ('Radiocasetofoane si DVD', 'sub-category', 26),
            ('Sisteme audio auto', 'sub-category', 26),
            ('Camere video auto', 'sub-category', 26),
            ('Sisteme de navigatie, GPS', 'sub-category', 26),
            ('Componente audio auto', 'sub-category', 26),
            ('Detectoare radar, alarme', 'sub-category', 26),
            ('Accesorii pentru salon', 'sub-category', 27),
            ('Covorase pentru masina', 'sub-category', 27),
            ('Vopsea Auto', 'sub-category', 27),
            ('Ajutor tehnic', 'sub-category', 27),
            ('Accesorii pentru caroserie', 'sub-category', 27),
            ('Scaune auto pentru copii', 'sub-category', 27),
            ('Portbagaje auto', 'sub-category', 27),
            ('Carinaj', 'sub-category', 27),
            ('Parktronic', 'sub-category', 27),
            ('Chei auto', 'sub-category', 27),
            ('Chei', 'sub-category', 28),
            ('Cricuri', 'sub-category', 28),
            ('Ascensoare', 'sub-category', 28),
            ('Demontatoare', 'sub-category', 28),
            ('Compresoare auto', 'sub-category', 28),
            ('Standuri de aliniere', 'sub-category', 28),
            ('incarcatoare de baterii auto', 'sub-category', 28),
            ('Aparate de spalat cu presiune', 'sub-category', 28),
            ('Echipamente de diagnoza', 'sub-category', 28),
            ('Echipament pentru montarea anvelopelor', 'sub-category', 28),
            ('Echipamente hidraulice si mecanice', 'sub-category', 28),
            ('Mobilier pentru statii de service', 'sub-category', 28),
            ('Unelte de lubrifiere', 'sub-category', 28),
            ('Echipamente de caroserie', 'sub-category', 28),
            ('Echipamente suplimentare', 'sub-category', 28),
            ('Uleiuri hidraulice', 'sub-category', 29),
            ('Uleiuri de viteze', 'sub-category', 29),
            ('Antigel', 'sub-category', 29),
            ('Lichid de frina', 'sub-category', 29),
            ('Lubrifianti', 'sub-category', 29),
            ('Uleiuri de motor', 'sub-category', 29),
            ('Lichide de spalat', 'sub-category', 29),
            ('Aditivi in ulei', 'sub-category', 30),
            ('Aditivi pentru combustibil', 'sub-category', 30),
            ('Aditivi pentru uleiul de viteze', 'sub-category', 30),
            ('Solutii de curatare', 'sub-category', 30),
            ('Aditivi pentru combustibil si dispersanti', 'sub-category', 30),
            ('Autoservice', 'sub-category', 31),
            ('Servicii de transport marfuri', 'sub-category', 31),
            ('Livrare din magazine', 'sub-category', 31),
            ('Auto la comanda', 'sub-category', 31),
            ('Servicii de transport pasageri', 'sub-category', 31),
            ('Мotoservice si veloservice', 'sub-category', 31),
            ('inchirieri transport', 'sub-category', 31),
            ('Accesorii spalat auto', 'sub-category', 32),
            ('sampon auto', 'sub-category', 32),
            ('Detergenti pentru caroserie', 'sub-category', 32),
            ('Polish auto', 'sub-category', 33),
            ('Solutii protectie caroserie', 'sub-category', 33),
            ('Cosmetica auto pentru interior', 'sub-category', 33),
            ('Cosmetica auto pentru jante', 'sub-category', 33),
            ('Cosmetica auto pentru sticla si faruri', 'sub-category', 33),
            ('Telefoane mobile', 'category', 3),
            ('Altele', 'category', 3),
            ('Diverse', 'category', 3),
            ('Gadget-uri', 'category', 3),
            ('Servicii', 'category', 3),
            ('Telefoane mobile', 'sub-category', 112),
            ('Accesorii', 'sub-category', 112),
            ('Piese de schimb pentru telefoane', 'sub-category', 112),
            ('Acumulatoare si incarcatoare', 'sub-category', 113),
            ('Statii radio', 'sub-category', 113),
            ('Telefoane fixe', 'sub-category', 113),
            ('Carduri de memorie', 'sub-category', 113),
            ('Statii telefonice', 'sub-category', 113),
            ('Aparate fax', 'sub-category', 113),
            ('Ceasuri inteligente', 'sub-category', 114),
            ('Drone ', 'sub-category', 114),
            ('Bratari fitness', 'sub-category', 114),
            ('Service si reparatii telefoane', 'sub-category', 115),
            ('Apartamente', 'category', 2),
            ('Case', 'category', 2),
            ('Loturi de teren', 'category', 2),
            ('Imobile comerciale', 'category', 2),
            ('Imobiliare strainatate', 'category', 2),
            ('Apartament cu 1 camera', 'sub-category', 130),
            ('Apartament cu 2 camere', 'sub-category', 130),
            ('Apartament cu 3 camere', 'sub-category', 130),
            ('Apartament cu 4 camere', 'sub-category', 130),
            ('Cu 5 si mai multe camere', 'sub-category', 130),
            ('Penthouses', 'sub-category', 130),
            ('Cu 1 nivel', 'sub-category', 131),
            ('Cu 2 niveluri', 'sub-category', 131),
            ('Cu 3 niveluri', 'sub-category', 131),
            ('Teren agricol', 'sub-category', 132),
            ('Teren pentru constructii', 'sub-category', 132),
            ('Teren cu lac', 'sub-category', 132),
            ('Teren cu lac', 'sub-category', 132),
            ('Spatii comerciale', 'sub-category', 133),
            ('Spatii productie', 'sub-category', 133),
            ('De inchiriat', 'sub-category', 133),
            ('Oficii', 'sub-category', 133),
            ('Depozite', 'sub-category', 133),
            ('Imobile Brasov', 'sub-category', 134),
            ('Imobile Bucuresti', 'sub-category', 134),
            ('Imobile Cluj', 'sub-category', 134),
            ('Imobile Sibiu', 'sub-category', 134),
            ('Imobile Iasi', 'sub-category', 134)
