INSERT INTO `shop`.`categories` (`name`, `type`, `groupId`) VALUES
            ('Transport', 'group', NULL),
            ('Imobiliare', 'group', NULL),
            ('Aparate telefonice și gadget-uri', 'group', NULL),
            ('Calculatoare și birotică', 'group', NULL),
            ('Construcții și reparații', 'group', NULL),
            ('Haine, încălțăminte și accesorii', 'group', NULL),
            ('Mobilă și interior', 'group', NULL),
            ('Mobilă și interior', 'group', NULL),
            ('Audio-Video-Foto', 'group', NULL),
            ('Diverse', 'group', NULL),
            ('Oferte de lucru', 'group', NULL),
            ('Gospodăria țărănească', 'group', NULL),
            ('Servicii', 'group', NULL),
            ('Animale de companie și plante', 'group', NULL),
            ('Sport, sănătate, frumusețe', 'group', NULL),
            ('Turism, recreație și divertisment', 'group', NULL),
            ('Business', 'group', NULL),
            ('Instrumente muzicale', 'group', NULL),
            ('Tehnică de uz casnic', 'group', NULL),
            ('Totul pentru sărbători', 'group', NULL),
            ('Lumea copiilor', 'group', NULL),
            ('Totul pentru casă și oficiu', 'group', NULL)
