INSERT INTO `shop`.`products` (`name`, `description`, `price`,`currency`, `groupId`, `subcategoryId`) VALUES
            ('BMW 5 Series',  'Bmw 520 Diesel x drive  4x4  sport line. Starea unui automobil nou atat estetic cat si tehnic. Completatie foarte bogata, scaune sport ,cauciucuri noi de iarna  ,cauciucuri de vara, incalzire scaune, 2 chei si  toata deservirea la dealer.','29 500', 'EUR', 1, 34),
            ('Volvo XC90',  'Primim automobile spre vînzare Adresa noastră: mun.Chișinău, str. Studenților nr.7/7, Parcul de Vînzări Date de contact ','17 500', 'EUR', 1, 34),
            ('Toyota Prius',  'Masina în stare foarte buna !!! Pret 11 500  pîna pe 02:04:2023','13 000', 'EUR', 1, 34),
            ('Audi A4',  'Masina este ingrijita! Km REALI! 170 HP! Merita de vazut! Nu SCHIMB! Sistemul de distributie GRM schimbat la 344.000 Toate actele valabile!','6 500', 'EUR', 1, 34),
            ('Nissan Note',  'Kilometraj motor 80.000 (a fost înlocuit în Franța de un dealer oficial înainte de export în MD) Toate actele sunt prezente, carte de service. Două chei. La bord sunt 300.000, dintre care 80.000 sunt în Moldova.','6 500', 'EUR', 1, 34),
            ('Porsche Cayenne',  'Masina adusa din Germania Complectatie bogata Starea foarte buna Nu necesita învestiții.','53 500', 'EUR', 1, 34),
            ('Toyota Rav 4',  'Salon piele neagra + alcantara Piele neagră Torpedo tavan negru Oglinzi electrice rabatabile Atingeți media Climat Navigare Cameră de vedere spate Două chei Anvelope de iarnă Inspectie tehnica si asigurare pana la 01.2024 Mașină viguroasă, plină de viață, în stare excelentă','20 300', 'EUR', 1, 34),
            ('Opel Astra',  'Masina la un singur proprietar, nu a fost lovita, motorul ideal nu consuma ulei, lucreaza linistit, foarte econom 5 l motorina prin oras, hodovaia fara nici o bataie, la moment nu necestia investitii se merita de vazut.','6 100', 'EUR', 1, 34),
            ('Iphone 13',  'Iphone 13 pro max midnight green folosit stare 9/10 baterie procent 93 800€','800', 'EUR', 3, 117),
            ('Samsung Galaxy A73',  'Smartphone-ul tău și-a pierdut capacitățile anterioare? Învechit? Defectat? E timpul să-i găsești un înlocuitor și cu siguranță te vom ajuta cu asta! Ai încredere în noi și nu te vom dezamăgi!','9 799', 'MDL', 3, 117),
            ('iPhone SE, 2022',  'Nou, nu a fost activat Model A2782 Se afla la botanica Pentru mai multe detalii scrieți va rog aici','8 899', 'MDL', 3, 117),
            ('Xiaomi 12T',  'Smartphone-ul tău și-a pierdut capacitățile anterioare? Învechit? Defectat? E timpul să-i găsești un înlocuitor și cu siguranță te vom ajuta cu asta! Ai încredere în noi și nu te vom dezamăgi!','9 499', 'MDL', 3, 117),
            ('Iphone 12 Pro',  'Smartphone-ul tău și-a pierdut capacitățile anterioare? Învechit? Defectat? E timpul să-i găsești un înlocuitor și cu siguranță te vom ajuta cu asta! Ai încredere în noi și nu te vom dezamăgi!','17 000', 'MDL', 3, 117),
            ('Redmi Note 10S',  'Smartphone-ul tău și-a pierdut capacitățile anterioare? Învechit? Defectat? E timpul să-i găsești un înlocuitor și cu siguranță te vom ajuta cu asta! Ai încredere în noi și nu te vom dezamăgi!','2 000', 'MDL', 3, 117),
            ('iPhone 11',  'Smartphone-ul tău și-a pierdut capacitățile anterioare? Învechit? Defectat? E timpul să-i găsești un înlocuitor și cu siguranță te vom ajuta cu asta! Ai încredere în noi și nu te vom dezamăgi!','2 000', 'MDL', 3, 117)

